### ISSUE TITLE
QuadraticRegularizer timestep normalization for free time problems

### ISSUE THREAD

**Issue by andgoldschmidt** [aarontrowbridge/QuantumCollocation.jl#50]
**Describe the bug**
`QuadraticRegularizer` is called on controls `a` to limit amplitudes. In a free time problem, the amplitude can be lowered if the timestep is increased. As a result, the pulse duration will only increase to improve regularization cost. The correct `QuadraticRegularizer` must divide the regularized value by the timestep size.

**To Reproduce**
Run a free time optimization. Compare the initial timestep to the timestep after the optimization. All timesteps will take larger values.

**Expected behavior**
`QuadraticRegularizer` should keep the control energy small. Amplitude constraints keep the control from exceeding some value.

**Comment by aarontrowbridge** [comment]
this was revised with PR #55 I believe?

**Comment by aarontrowbridge** [comment]
should be an integral regulizer, which was added -- closing.
