### ISSUE TITLE
add ability to not have a drift hamiltonian

### ISSUE THREAD

**Issue by aarontrowbridge** [aarontrowbridge/QuantumCollocation.jl#59]
**Is your feature request related to a problem? Please describe.**
Currently, if a problem doesn't have a drift Hamiltonian a matrix of zeros must be passed in its place.

**Describe the solution you'd like**
It would be nice to have a constructor method that omits the drift term.

**Comment by andgoldschmidt** [comment]
Sparse quantum system matrices in version 0.2.0
