### ISSUE TITLE
[Feature]: interface with QuantumOptics.jl

### ISSUE THREAD

**Issue by aarontrowbridge** [aarontrowbridge/QuantumCollocation.jl#85]
### Feature Description

It would be great to have the functionality to build `QuantumSystem`s using [operators](https://docs.qojulia.org/quantumobjects/operators/) from QuantumOptics.jl. This should be a very simple PR that adds a dependency for QuantumOptics and creates a method for [`QuantumSystem`](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/86ae355abff314b4dc6ac98591b51ae626fdac71/src/quantum_systems.jl#L102). 

#### Implementation Guidelines

- A file should be added to the directory [`src/quantum_system_templates`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/src/quantum_system_templates), matching the style of the files therein.
- Add a doc script to the folder [`docs/literate/man`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/docs/literate/man)
  - see the [Literate.jl](https://github.com/fredrikekre/Literate.jl) docs and the other scripts in the `docs/literate` folder
- Add a file to [`test`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/test) with some simple tests for the functions exported
 

### Importance

2

### What does this feature affect?

- [X] quantum system construction
- [ ] problem setup
- [ ] problem solution
- [ ] problem performance
- [ ] solution analysis
- [ ] plotting
- [ ] documentation
- [ ] tests
- [ ] other (please specify below)

**Comment by aarontrowbridge** [comment]
I think this should potentially interface with [`QuantumToolbox.jl`](https://github.com/qutip/QuantumToolbox.jl), if this is implemented using that we can close this issue.

**Comment by maxwell04-wq** [comment]
I'm currently working on this issue. However, I am stuck at implementing the quantum optics system, especially the Hamiltonians for the systems to be implemented. Can you please share a reference paper, article, etc. for help in the implementation?

**Comment by aarontrowbridge** [comment]
Ideally the operators will be sparse matrices, see this [method](https://docs.qojulia.org/api/#QuantumOpticsBase.SparseOperator) in quantum optics for getting sparse representations
