### ISSUE TITLE
[Feature]: unsymmetric constraints on the pulses and first order derivative constraints of the pulses

### ISSUE THREAD

**Issue by hongyehu** [aarontrowbridge/QuantumCollocation.jl#90]
### Feature Description

In quantum control using the ansatz Hamiltonian: $H(t) = H_{drift} + \sum_{i} a_{i}(t)H_{i}$. Sometimes the machine requires:
1. unsymmetric constraints, $a_i(t)\in [a_{min},a_{max}]$, where $a_{min}\neq - a_{max}$. For example, $a_{i}(t)\in [0,2.5]$.
2. slope constraints: sometimes, machine requires $$|(a_{i}(t_{l+1})-a_{i}(t_{l}))/(t_{l+1}-t_{l})| \leq C$$ for piecewise linear function or $| da_{i}(t) / dt | \leq C$ for true continuous pulse. (But the machine uses piecewise linear even if one provides continuous function mostly)
It would be great to add a new feature to set those two constraints in the solver!

### Importance

5 (highest)

### What does this feature affect?

- [ ] quantum system construction
- [X] problem setup
- [X] problem solution
- [X] problem performance
- [ ] solution analysis
- [ ] plotting
- [ ] documentation
- [ ] tests
- [ ] other (please specify below)

### Other information

related to a deadline for experiments.

**Comment by andgoldschmidt** [comment]
Both of these are hidden by the problem template structure, but you can get more fine-grained control over the problem data if we look one layer deeper. Check out this fragment from the `UnitarySmoothPulseProblem` (line ~206)
```Julia
components = (
    Ũ⃗ = Ũ⃗,
    a = a,
    da = da,
    dda = dda,
)

bounds = (
    a = a_bounds,
    dda = dda_bounds,
)

traj = NamedTrajectory(
    components;
    controls=(:dda,),
    timestep=Δt,
    bounds=bounds,
    initial=initial,
    final=final,
    goal=goal
)
```

1. You can directly specify the bounds you'd like. In a `UnitarySmoothPulseProblem`, we use symmetric bounds. However, bounds is just a tuple with the form: `([lower, vector, entries], [upper, vector, entries])`. The number of vector entries should correspond to the number of controls in the control matrix.

2. The slope constraint can be set using a `da_bound`. In a `UnitarySmoothPulseProblem`, we use $\ddot{a}$ as the control variable---it is Euler integrated twice to get back to $a$. Hence, you have direct access to $\dot{a}$ and can append your constraint, mimicking the style of the others.

**Comment by andgoldschmidt** [comment]
Our recommended workflow is to write a new problem template that is adapted to your desired problem. You can start from an existing template and make piecemeal changes to adapt it to your needs. 

One current goal is to document this workflow and make our problem templates into much cleaner minimal working examples to better enable this workflow.

**Comment by andgoldschmidt** [comment]
Closing with a note to improve docs and template flexibility.
